version: '3'

services: 
    app:
        build: .
        container_name: example-node-splunk-docker
        image: example-node-splunk-docker:latest
        environment: 
            - SPLUNK_HOST=splunk
        ports: 
            - "5000:5000"
    splunk:
        image: splunk/splunk:latest
        hostname: splunk
        container_name: splunk
        environment:
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_PASSWORD=senha123
            - SPLUNK_LICENSE_URI=Free
        volumes: 
            - ./splunk/local:/opt/splunk/etc/apps/splunk_httpinput/local
        ports:
            - "8000:8000"
            - "8088:8088"